default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: postgres
  port: 5432
  host: localhost
  database: webnoveltoebook_development

test:
  <<: *default
  username: postgres
  password: postgres
  port: 5432
  host: localhost
  database: webnoveltoebook_test

production:
  <<: *default
  database: webnoveltoebook_production
  username: webnoveltoebook
  password: <%= ENV['WEBNOVELTOEBOOK_DATABASE_PASSWORD'] %>
